# Generated by Django 4.1 on 2022-09-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='BookName',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='topic',
            new_name='bookname',
        ),
    ]
