# Generated by Django 4.1 on 2022-09-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_topic_bookname_rename_topic_posts_bookname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='bookname',
            new_name='book_name',
        ),
    ]
