# Generated by Django 4.1 on 2022-09-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_bookname_posts_book_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookName',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='book_name',
            new_name='book',
        ),
    ]
