# Generated by Django 4.1 on 2022-09-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_bookname_book_rename_book_name_posts_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
