# Generated by Django 4.1 on 2022-09-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_users_bio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
